export default {
	$schema: 'https://son.schemastore.org/prettierrc',
	semi: true,
	singleQuote: true,
	printWidth: 150,
	singleAttributePerLine: true,
	trailingComma: 'none',
	useTabs: true,
	tabWidth: 2,
	bracketSameLine: true,
	arrowParens: 'avoid',
	bracketSpacing: true,
	htmlWhitespaceSensitivity: 'css',
	quoteProps: 'as-needed',
	jsxSingleQuote: false,
	jsxBracketSameLine: false,
	rangeStart: 0,
	requirePragma: false,
	insertPragma: false,
	overrides: [],
	endOfLine: 'auto',
	proseWrap: 'preserve',
	embeddedLanguageFormatting: 'auto'
};
